### ISSUE TITLE
How can I run this code 

### ISSUE THREAD

**Issue by Ayman-Adel-memo** [Khandakar227/arduino-and-gamepad-communication-with-python#2]

**Comment by Khandakar227** [comment]
What issues have you faced?
Add your bluetooth module's MAC address to bd_addr variable in bt.py.
Run gp.py from your terminal to check gamepad's output.

If your on linux you may face issue with pybluez like **libbluetooth-dev** is not installed. You can install it with apt. Let me know what have u tried?
